### ISSUE TITLE
Make your PA repos private (Academic Integrity violation)

### ISSUE THREAD

**Issue by niemasd** [jingkai02/datathon_2021#1]
By posting your PA code publicly, you are explicitly violating the Academic Integrity policy of CSE 100. You need to make all of your PA repos private, otherwise I will have to report this to the Academic Integrity Office.

Specifically, I'm not sure how the following directory ended up here:

https://github.com/jingkai02/datathon_2021/tree/main/BFS_implementation_c%2B%2B

But please undo the commit that added these files, which seem to have been added by @SaamJi

**Comment by jingkai02** [comment]
Thanks for alerting us of this, this repo has since been made private

**Comment by SaamJi** [comment]
Hi professor Moshiri,

Again thanks for the alert. I was a student at CSE100, and I’m the one who
committed it to the repo because I wasn’t aware that this violates the
Academic Integrity. I’ve deleted all the files, and we’ve made the repo
private as well. Please let me know if we need to do anything further.

Thanks,
Sam Ji
